general/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
import bvn_validation
import views, paystack_helpers
import sokohali_views, group_access
import user_profile
from django.views.generic import TemplateView

from general.models import *


user_account = [
                url(r'^user-account/profile/(?P<username>.+)/$', user_profile.profile, name='profile'),
                url(r'^user-account/edit-profile/(?P<username>.+)/$', user_profile.edit_profile, name='edit_profile'),
                url(r'^volk/user-account/profile/(?P<username>.+)/$', user_profile.profile_volk, name='profile_volk'),
                url(r'^volk/user-account/edit-profile/(?P<username>.+)/$', user_profile.edit_profile_volk, name='edit_profile_volk'),
                url(r'^user-account/address-activation/(?P<username>.+)/$', user_profile.address_activation, name='address_activation'),
                url(r'^volk/user-account/address-activation/(?P<username>.+)/$', user_profile.address_activation_new, name='address_activation_new'),
                url(r'^user-account/bvn/verification/$', bvn_validation.verify, name ="verify_bvn"),
                url(r'^user-account/otp/verification/$', bvn_validation.enter_otp, name ="enter_otp"),
                url(r'^user-account/otp/validation/$', bvn_validation.validation_result, name ="validate_otp"),
                url(r'^user-account/resend/otp/$',bvn_validation.resend_otp, name="resend_otp"),
]


sokohali_urls = [
                 url(r'^sokohali/logout/$', sokohali_views.sokohali_logout, name="sokohali-logout"),
                 url(r'^business-settings/$', sokohali_views.business_settings, name="business_settings"),
                 url(r'^about/$', sokohali_views.about, name="about"),
                 url(r'^demo/$', sokohali_views.demopage, name="demopage"),
                 url(r'^contact/$', sokohali_views.contact, name="contact"),
                 url(r'^legal/$', sokohali_views.legal, name="legal"),
                 url(r'^login/$', sokohali_views.LoginSubscriber.as_view(), name="subscriber_login"),
                 url(r'^register/$', sokohali_views.register, name="subscriber_register"),
                 url(r'^sokohali/subscriber-profile/(?P<username>.+)/$', sokohali_views.subscriber_profile, name='subscriber_profile'),
                 url(r'^sokohali/subscriber-edit-profile/(?P<username>.+)/$', sokohali_views.subscriber_edit_profile, name='subscriber_edit_profile'),
                 url(r'^password/$', sokohali_views.change_password, name='change_password'),
                 url(r'^passwordrequest/$', sokohali_views.passwordrequest, name='passwordrequest'),

]

urlpatterns = [

                url(r'^', include(user_account)),
                url(r'^', include(sokohali_urls)),


                url(r'^user/login/$', views.LoginRequest.as_view(), name="login"),
                url(r'^volk/login/$', views.LoginRequestNew.as_view(), name="volkLogin"),
                url(r'^user/logout/$', views.logoutRequest, name="logout"),
                url(r'^user/signup/$', views.userregistration_regular, name="signup_regular"),
                url(r'^user/suspension/$', views.suspension, name="suspension"),
                url(r'^marketer-home/$', views.homepage, name="marketer_home"),
                url(r'^domestic-shipping/$', views.domestic_shipping, name='domestic'),
                url(r'^contact-us-volk/$', views.contact_us_volk, name="contact_us_volk"),
                url(r'^contact-us/$', views.contact_us, name="contact_us"),
                url(r'^shopForMe/$', views.vei_shopper, name="vei_shopper"),
                
                url(r'^zeac/contact-us/$', views.zeac_contct_us, name="zeac_contct_us"),

                url(r'^shopping/(?P<action>.+)/(?P<item_id>[-\w]+)/(?P<amount>\d+\.\d{1})/$', views.crud_pay_for_shop, name="crud_pay_for_shop"),
                url(r'^get-dropoff-locations', views.get_dropoff_locations, name="get_dropoff_locations"),
                url(r'^get-location-address', views.get_location_address, name="get_location_address"),
                url(r'^get-country-regions', views.get_country_regions, name="get_country_regions"),
                url(r'^distributor_api_or_rates', views.distributor_api_or_rates, name="distributor_api_or_rates"),
                url(r'^warehouse-address', views.get_warehouse_address, name = "get_warehouse_address"),
                url(r'^my-account/$', views.user_account, name="my_account"),
                url(r'^dst-warehouse-address', views.get_destination_addresses, name = "get_destination_addresses"),
                url(r'^my-shipments/$', views.my_shipments, name="my_shipments"),
                url(r'^volk/shipments/$', views.my_shipments_volk, name="my_shipments_volk"),
                url(r'^my-orders/$', views.my_orders, name="my_orders"),
                url(r'^my-payments/$', views.my_soko_pay_info, name="my_payments"),
                url(r'^volk/payments/$', views.my_soko_pay_info_volk, name="my_payments_volk"),
                url(r'^my-messages/$', views.my_messages, name="my_messages"),
                url(r'^volk/messages/$', views.my_messages_volk, name="my_messages_volk"),
                url(r'^check-avaliable-routes/$', views.check_avaliable_routes, name="check_avaliable_routes"),
                url(r'^my-delivery-addresses/$', views.view_delivery_addresses, name="delivery-addresses"),
                url(r'^volk/delivery-addresses/$', views.view_delivery_addresses_volk, name="delivery_addresses_volk"),
                url(r'^my-mail-bag/$', views.my_mail_bag, name="my_mail_bag"),
                url(r'^volk/mail-bag/$', views.my_mail_bag_volk, name="my_mail_bag_volk"),
                url(r'^paystack/verifyPayment/$',paystack_helpers.verify_payment, name="verifyPayment"),
                url(r'^my-shipment/(\d+)/cancel/$', views.cancel_shipment, name="cancel_shipment"),
                url(r'^FAQ/$', views.marketerFAQ, name = "faq"),
                url(r'^terms-and-conditions/$', views.legal, name = "legal"),
                url(r'^auto-deals/$', views.iaai, name = "iaai"),
                url(r'^waitinglist/$', views.joinwaitinglist, name="joinwaitinglist"),
                url(r'^sendmail/(?P<username>.+)/(?P<subject>.+)/(?P<text>.+)$', views.sendmail, name="sendmail"),
                url(r'^marketer-addon/(?P<action>.+)/$',views.marketer_addons, name="marketer_addons"),
                url(r'^view_edit_shopping_item_order/$',views.view_edit_shopping_item_order, name="view_edit_shopping_item_order"),
                url(r'^edit_shop_request/$',views.edit_shop_request, name="edit_shop_request"),
                
                url(r'^product-view/$', views.product_view, name="product_view"),
                url(r'^detail-view/(?P<item_id>[-\w]+)/$', views.detail_view, name='detail_view'),
                url(r'^cart-view/$', views.cart_view, name="cart_view"),
                url(r'^delete-item/(?P<item_id>[-\w]+)/$', views.delete_item, name='delete_item'),
                url(r'^delete-inv-item/(?P<item_id>[-\w]+)/$', views.del_inv, name='del_inv'),
                url(r'^edit-inv-item/$', views.edit_inv, name='edit_inv'),
                url(r'^inv-edited/$', views.inv_edited, name='inv_edited'),
                url(r'^view-item/$', views.view_item, name='view_item'),
                url(r'^inv-sidebar-category/$', views.inv_sidebar_category, name='inv_sidebar_category'),
                url(r'^checkout/$', views.checkout, name="checkout"),
                url(r'^checking-out-page/$', views.checking_out, name="checking_out"),
                url(r'^order-summary/$', views.order_summary, name="order_summary"),
                url(r'^add-to-cart/$', views.add_to_cart, name="add_to_cart"),
                url(r'^add-inventory/$', views.add_inventory, name="add_inventory"),
                url(r'^inventory/history/(?P<item_id>[0-9]+)$', views.inv_history, name="inventory_history"),
                url(r'^pay-options/$', views.pay_options, name="pay_options"),
                url(r'^order-confirmation/$', views.order_confirmation, name="order_confirmation"),
                url(r'^track_shipments/$', views.track_shipments, name="track_shipments"),
                url(r'^volk/shipment-detail/$', views.shipment_detail_volk, name="shipment_detail_volk"),
                url(r'^volk/detail-shipment/$', views.shipment_detail_number_volk, name="shipment_detail_number_volk"),
                url(r'^volk/shipment-tracker/$', views.my_tracker_volk, name="my_tracker_volk"),
                

                # quick estimate
                url(r'^quick-estimate$', views.quickEstimate, name="quick-estimate"),

                # test label printing
                url(r'^print-label$', views.test_label_printing, name="test_label_printing"),

                # pay-pal
                url(r'^confirm_paypal_payment/$', views.confirm_paypal_payment, name="confirm_paypal_payment"),

                # ebiz
                url(r'^confirm_ebiz_payment/$', views.confirm_ebiz_payment, name="confirm_ebiz_payment"),

                # staff access 
                url(r'^admin-access/(?P<user_obj>.+)/$', group_access.admin_access, name="admin_access"),
                url(r'^zeac/estimate/$', views.get_estimate, name="get_estimate"),
                # url(r'^subscribers-password/$', sokohali_views.change_password, name='change_password'),

]

sokohaliv2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.shortcuts import render, render_to_response

from django.template import RequestContext
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap

from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from general.user_profile import redirect_to_address_activation, redirect_to_address_activation_new
from general.custom_resetpassword import custom_password_reset, custom_password_reset_done
from general.views import homepage

from general.barcode_generator import create_test_barcode


#server error
def server_error(request):
    response = render(request, "500.html")
    response.status_code = 500
    return response

#page not found
def custom_404(request):
    response = render(request, "404.html")
    response.status_code = 404
    return response

#access denied
def access_denied(request):
    return render_to_response("access_denied.html", {},
                              context_instance=RequestContext(request))

handler404 = custom_404

handler500 = server_error


urlpatterns = [

    # url(r'^$', TemplateView.as_view(template_name = 'index.html'), name='homepage'),
    url(r'^$', homepage, name='homepage'),

    #temporary measure
    url(r'^marketer/$', homepage, name='marketer_homepage'),

    url(r'^', include("general.urls", namespace="general")),

    url(r'^adminVolkmann/', include(admin.site.urls)),

    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^payment/', include("payment.urls", namespace="payment")),

    url(r'^', include("veiwallet.urls", namespace="wallet")),

    url(r'^access-denied/$', access_denied, name='access_denied'),

    url(r'session_security/', include('session_security.urls')),

    url(r'^registration/successful/$', TemplateView.as_view(template_name = 'general_client/regsuccessful.html'), name="reg_successful"),

    url(r'^successful/reg/$', TemplateView.as_view(template_name = 'volkmann/registration_successful.html'), name="successful_reg"),

    #Address Activation
    url(r'^redirect_to_address_activation/', redirect_to_address_activation),

    url(r'^redirect_to_address_activation_new/', redirect_to_address_activation_new),

    #import shipping
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),

    #pkg-processor
    url(r'^pkg-processor-api/', include('pkg_processor.urls')),

    url(r'^setup/', include("service_provider.urls", namespace="service_provider")),

    #SokohaliAdmin
    url(r'^backend/', include("sokohaliAdmin.urls", namespace="sokohaliAdmin")),

    url(r'^pay/', include('sokopay.urls', namespace = "soko_pay")),

    url(r'^shopping/', include('shoppingCenter.urls', namespace = "shoppingCenter")),

    url(r'^create-test-barcode/(?P<barcode_id>.+)/', create_test_barcode),

    #change password urls
    url(r'^reset/form/$', TemplateView.as_view(template_name = 'registration/password_reset_email.html')),
    url(r'^resetpassword/passwordsent/$', custom_password_reset_done, name="password_reset_done"),
    #url(r'^resetpassword/$', password_reset, name="password_reset"), custom_password_reset
    url(r'^resetpassword/$', custom_password_reset, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset/done/$', password_reset_complete, name="password_reset_complete"),




]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sokopay/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
#from views import add_funds, user_transactions, pay_with_zappay_credit, pay_by_bank_deposit
import views

from general.paystack import verify_transaction
from general import flutterwave_helpers

urlpatterns = [
            url(r'^$', TemplateView.as_view(template_name = 'soko_pay/soko_pay.html'), name="soko_pay"),
            url(r'^transactions/$', views.user_transactions, name="user_transactions"),
            url(r'^add-funds/$', views.add_funds, name="add_funds"),
            url(r'^add-funds-volk/$', views.add_funds_volk, name="add_funds_volk"),
            url(r'^funds-volk-card/$', views.add_funds_volk_card, name="add_funds_volk_card"),
            url(r'^add-funds-card/$', views.buy_jejepay_credit_card, name="buy_jejepay_credit_card"),
            url(r'^add-funds-page/$', TemplateView.as_view(template_name = 'soko_pay/add_funds_landing_page.html'), name="add_funds_landing_page"),
            url(r'^subscriber/card-payment/$', views.SubCardPayment, name="sub_card_payment"),
            url(r'^select-payment-option/$', views.select_payment_option, name="select_payment_option"),
            url(r'^pay-balance/$', views.pay_balance, name="pay_balance"),
            url(r'^pay_for_shipments/$', views.pay_for_shipments, name="pay_for_shipments"),
            url(r'^pay_for_package/$', views.pay_for_package, name="pay_for_package"),
            #flutterwave callback url
            url(r'^intl-card-verification/$', flutterwave_helpers.intl_card_verification, name='intl_card_verification'),
            url(r'^complete-intl-card/$', flutterwave_helpers.complete_intl_card, name='complete_intl_card'),

            #paystack callback url
            url(r'^paystack/(?P<jejepay_ref>\d+)/(?P<dest_namespace>.+)/$', verify_transaction, name="paystack_verify_transaction"),
            url(r'^pay-with-zappay-credit/(?P<shop_or_ship>.+)/(?P<id>.+)/$', views.pay_with_zappay_credit, name="pay_with_zappay_credit"),
            url(r'^pay-by-bank-deposit/(?P<id>.+)/$', views.pay_by_bank_deposit, name="pay_by_bank_deposit"),
            url(r'^subscriber/payment/$', views.subscriberPayment, name ="sub_payments"),
            
            #url(r'^select-payment-option/(?P<shop_or_ship>.+)/(?P<id>.+)/$', views.select_payment_option, name="select_payment_option"),

    ]

sokopay/forms.py
from django.forms import ModelForm
from models import SokoPay, MarketerPayment


class SokoPayForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SokoPayForm, self).__init__(*args, **kwargs)

    class Meta:
        model = SokoPay
        #fields = ('amount',)
        exclude = ('purchase_type_1','payment_gateway_tranx_id', 'teller_no', 'created_at', 'status', 'exchange_rate')
        
        
class SokoPayAddForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SokoPayAddForm, self).__init__(*args, **kwargs)

    class Meta:
        model = SokoPay
        #fields = ('amount',)
        exclude = ('payment_gateway_tranx_id', 'created_at', 'status', 'exchange_rate')
        
        
class MarketerPaymentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(MarketerPaymentForm, self).__init__(*args, **kwargs)
        
    class Meta:
        model = MarketerPayment
        fields = ('amount', 'payment_channel', 'ref_no', 'bank', 'teller_no',)
        #exclude = ('payment_gateway_tranx_id', 'created_at', 'status', 'message', 'marketer','package')

sokopay/templates/soko_pay/pay_for_pkg_landing_page.html
{% extends "base/zaposta_base.html" %}


{% block title %}Pay Package outstanding balance{% endblock %}
{% block extra_head %}
<style>
    div.modal-backdrop.fade.in{
        z-index: 0 !important;
    }
    .shipping.two{
        width: 370px !important;
    }
    .shopping.two{
        width: 370px !important;
    }
</style>

{% endblock %}

{% block body_head %}
<body>
{% endblock %}


{% block st_content %}
<!-- this is the wrapper for the content -->
                <div class="st-content-inner">
                    <!-- extra div for emulating position:fixed of the menu -->
                    <!-- Main Section -->
                    <section id="main" class="payment_main">
                        <!-- place widget -->
                        <div class="wt two">
                            <div class="container" style="position:relative;">
                                <!--<img src="img/ism1.png" />
                                <p>21:04</p>
                                <img src="img/ism2.png" />
                                <p>London, UK</p>-->
                            </div>
                        </div>
                        <!-- place widget -->
                        <div class="hero t" id="payment_page">
                            <div class="container outer">

                                <div class="landing_inner">
                                    <!--<div class="shipping two">
                                        <div class="col-md-12">
                                                <div style="padding-top: 50px; text-align: center;">
                                                    <img src="{{STATIC_URL}}shopping/images/payment_icon3.png" style="margin-left: 10px;"/>
                                                    <img src="{{STATIC_URL}}shopping/images/uba_copy.png" style="margin-left: 10px;"/>
                                                </div>

                                                <h4>Account Name: Sokohali</h4>
                                                <h4>GTB Number: 0171988384</h4>

                                                <img src="{{STATIC_URL}}shopping/images/uba_copy.png" style="margin-left: 10px; margin-top: 10px;"/>
                                                <h4>Account Name: Sokohali</h4>
                                                <h4>UBA Account: 1019192708</h4>

                                            <div>
                                                <a href="{% url 'soko_pay:add_funds' %}" class="btn">Bank Deposit</a>
                                                <a href="#" class="btn">Bank Deposit</a>
                                            </div>
                                        </div>
                                    </div>-->

                                    <div class="shipping two">
                                        <div class="col-md-12">
                                            <div style="padding-top: 50px; text-align: center;">
                                                <img src="{{STATIC_URL}}zaposta/img/zappay2.png" style="margin-left: 10px; width: 200px;"/>  <!-- IMG -->
                                            </div>

                                            <div>
                                                <!--<a href="{% url 'soko_pay:add_funds' %}" class="btn">Bank Deposit</a>-->
                                                <a href="#" class="btn" style="margin-top: 72px;">Pay</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="shopping two">
                                        <div class="col-md-12">
                                            <div style="padding-top: 50px; text-align: center;">
                                                <img src="{{STATIC_URL}}export/img/cc/verve.png" width="70px" height="30px"/>
                                                <img src="{{STATIC_URL}}shopping/images/mastercard.png" width="70px" style="margin-left: 10px;"/>  <!-- IMG -->
                                                <img src="{{STATIC_URL}}shopping/images/visa.png" width="70px" style="margin-left: 10px;"/>  <!-- IMG -->
                                            </div>

                                            <div>
                                                <a href="{% url 'soko_pay:buy_jejepay_credit_card' %}" class="btn" style="width: 40%;">Pay</a>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="shipping two">
                                        <div class="col-md-12">
                                            <div style="padding-top: 50px; text-align: center;">
                                                <img src="{{STATIC_URL}}export/img/cc/paypal.png" style="margin-left: 10px; height: 70px;"/>  <!-- IMG -->
                                            </div>

                                            <div>
                                                <!--<a href="{% url 'soko_pay:add_funds' %}" class="btn">Bank Deposit</a>-->
                                                <a href="#" style="margin-top: 70px;"  class="btn">Pay</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </section>
                    <!-- Main Section -->

                    <!-- FOOTER  -->
                    <footer class="black two">
                        {% include 'zaposta_snippet/footer-bottom.html' %}
                    </footer>
                    <!-- FOOTER  -->
                </div>
                <!-- /st-content-inner -->

<!-- /st-content-inner -->
{% endblock %}

sokopay/templates/soko_pay/select_payment_option.html
{% extends "base/zaposta_base.html" %}


{% block title %}Select Payment Option{% endblock %}
{% block extra_head %}
<style>
    div.modal-backdrop.fade.in{
        z-index: 0 !important;
    }
    .shipping.two{
        /*width: 370px !important;*/
        border-style: solid;
        border-radius: 10px;
        border-color: black;
    }
    .shipping.two p{
        color: black;
    }
    /*.shopping.two{
        width: 370px !important;
    }*/
</style>

{% endblock %}

{% block body_head %}
<body>
{% endblock %}


{% block st_content %}
<!-- this is the wrapper for the content -->
                <div class="st-content-inner">
                    <!-- extra div for emulating position:fixed of the menu -->
                    <!-- Main Section -->
                    <section id="main" class="payment_main">
                        <!-- place widget -->
                        <div class="wt two">
                            <div class="container" style="position:relative;">
                                <!--<img src="img/ism1.png" />
                                <p>21:04</p>
                                <img src="img/ism2.png" />
                                <p>London, UK</p>-->
                            </div>
                        </div>
                        <!-- place widget -->
                        <div class="hero t" id="payment_page">
                            <div class="container outer">

                                <div class="landing col-md-12" style="position: relative; padding-top: 38px;">
                                    <div class="shipping two col-md-6">
                                        <div class="col-md-12">
                                                {% if not mm.banking_details %}
                                                    <div style="padding-top: 50px; text-align: center;">
                                                        <img src="{{STATIC_URL}}shopping/images/payment_icon3.png" style="margin-left: 10px;"/>
                                                        <img src="{{STATIC_URL}}shopping/images/uba_copy.png" style="margin-left: 10px; "/>
                                                    </div>
                                                    <div>
                                                        <a href="#" style="position: relative;width: 250px; top:18px;" class="btn">Bank Deposit Not available</a>
                                                    </div>
                                                {% else %}
                                                
                                                    {% for bank in mm.banking_details %}
                                                        <div class="" style="margin-top: 0px;">
                                                            <p>Bank: {{bank.bank}} | 
                                                               Account Name: {{bank.account_name}} | 
                                                               Account Number: {{bank.account_no}}
                                                            </p>
                                                        </div>
                                                    {% endfor %}
                                                    <!--<img src="{{STATIC_URL}}shopping/images/uba_copy.png" style="margin-left: 10px; margin-top: 10px;"/>-->
                                                    <!--<h4>Account Name: Sokohali</h4>
                                                    <h4>UBA Account: 1019192708</h4>-->
                                                    <div>
                                                        <a href="{% url 'soko_pay:pay_by_bank_deposit' tracking_number %}" style="position: relative;width: 250px; top:30px; margin-top: 0px!important;" class="btn">Bank Deposit</a>
                                                    </div>
                                                {% endif %}
                                        </div>
                                                
                                                <!--<a href="#" class="btn">Bank Deposit</a>-->
                                    </div>
                                       

                                    <div class="shipping two col-md-6">
                                        <div class="col-md-12">
                                            <div style="padding-top: 50px; text-align: center;">
                                                <img src="{{STATIC_URL}}sokohali/img/soko_pay_thumb.jpg" style="margin-left: 10px; width: 15%;"/>  <!-- IMG -->
                                            </div>

                                            <div>
                                                <!--<a href="{% url 'soko_pay:add_funds' %}" class="btn">Bank Deposit</a>-->
                                                <a href="{% url 'soko_pay:pay_balance' %}?tracking_number={{ tracking_number }}&pay_method=SokoPay" class="btn" style="margin-top: 93px;">SokoPay</a>
                                            </div>
                                        </div>
                                    </div>


                                    <div class="shipping two col-md-6">
                                        <div class="col-md-12">
                                            <div style="padding-top: 50px; text-align: center;">
                                                <img src="{{STATIC_URL}}export/img/cc/verve.png" width="70px" height="30px"/>
                                                <img src="{{STATIC_URL}}shopping/images/mastercard.png" width="70px" style="margin-left: 10px;"/>  <!-- IMG -->
                                                <img src="{{STATIC_URL}}shopping/images/visa.png" width="70px" style="margin-left: 10px;"/>  <!-- IMG -->
                                            </div>

                                            <div style="padding-top: 30px;">
                                                <a href="{% url 'soko_pay:pay_balance' %}?tracking_number={{ tracking_number }}&pay_method=Card" class="btn" style="width: 40%;">Pay</a>
                                                <!--<span>Coming Soon...</span>-->
                                            </div>

                                        </div>
                                    </div>


                                    <div class="shipping two col-md-6">
                                        <div class="col-md-12">
                                            <div style="padding-top: 50px; text-align: center;">
                                                <img src="{{STATIC_URL}}export/img/cc/paypal.png" style="margin-left: 10px; height: 70px;"/>  <!-- IMG -->
                                            </div>

                                            <div>

                                               <a href="{% url 'soko_pay:pay_balance' %}?tracking_number={{ tracking_number }}&pay_method=PP" class="btn" style="margin-top: 93px;">PayPal</a>

<!--                                                 <a href="#"</a>
 -->                                            
                                            </div>
                                        </div>
                                    </div>


                                </div>
                            </div>

                        </div>
                    </section>
                    <!-- Main Section -->

                    <!-- FOOTER  -->
                    <footer class="black two">
                        {% include 'zaposta_snippet/footer-bottom.html' %}
                    </footer>
                    <!-- FOOTER  -->
                </div>
                <!-- /st-content-inner -->

<!-- /st-content-inner -->
{% endblock %}