general/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
import bvn_validation
import views, paystack_helpers
import sokohali_views, group_access
import user_profile
from django.views.generic import TemplateView

from general.models import *


user_account = [
                url(r'^user-account/profile/(?P<username>.+)/$', user_profile.profile, name='profile'),
                url(r'^user-account/edit-profile/(?P<username>.+)/$', user_profile.edit_profile, name='edit_profile'),
                url(r'^volk/user-account/profile/(?P<username>.+)/$', user_profile.profile_volk, name='profile_volk'),
                url(r'^volk/user-account/edit-profile/(?P<username>.+)/$', user_profile.edit_profile_volk, name='edit_profile_volk'),
                url(r'^user-account/address-activation/(?P<username>.+)/$', user_profile.address_activation, name='address_activation'),
                url(r'^volk/user-account/address-activation/(?P<username>.+)/$', user_profile.address_activation_new, name='address_activation_new'),
                url(r'^user-account/bvn/verification/$', bvn_validation.verify, name ="verify_bvn"),
                url(r'^user-account/otp/verification/$', bvn_validation.enter_otp, name ="enter_otp"),
                url(r'^user-account/otp/validation/$', bvn_validation.validation_result, name ="validate_otp"),
                url(r'^user-account/resend/otp/$',bvn_validation.resend_otp, name="resend_otp"),
]


sokohali_urls = [
                 url(r'^sokohali/logout/$', sokohali_views.sokohali_logout, name="sokohali-logout"),
                 url(r'^business-settings/$', sokohali_views.business_settings, name="business_settings"),
                 url(r'^about/$', sokohali_views.about, name="about"),
                 url(r'^demo/$', sokohali_views.demopage, name="demopage"),
                 url(r'^contact/$', sokohali_views.contact, name="contact"),
                 url(r'^legal/$', sokohali_views.legal, name="legal"),
                 url(r'^login/$', sokohali_views.LoginSubscriber.as_view(), name="subscriber_login"),
                 url(r'^register/$', sokohali_views.register, name="subscriber_register"),
                 url(r'^sokohali/subscriber-profile/(?P<username>.+)/$', sokohali_views.subscriber_profile, name='subscriber_profile'),
                 url(r'^sokohali/subscriber-edit-profile/(?P<username>.+)/$', sokohali_views.subscriber_edit_profile, name='subscriber_edit_profile'),
                 url(r'^password/$', sokohali_views.change_password, name='change_password'),
                 url(r'^passwordrequest/$', sokohali_views.passwordrequest, name='passwordrequest'),

]

urlpatterns = [

                url(r'^', include(user_account)),
                url(r'^', include(sokohali_urls)),


                url(r'^user/login/$', views.LoginRequest.as_view(), name="login"),
                url(r'^volk/login/$', views.LoginRequestNew.as_view(), name="volkLogin"),
                url(r'^user/logout/$', views.logoutRequest, name="logout"),
                url(r'^user/signup/$', views.userregistration_regular, name="signup_regular"),
                url(r'^user/suspension/$', views.suspension, name="suspension"),
                url(r'^marketer-home/$', views.homepage, name="marketer_home"),
                url(r'^domestic-shipping/$', views.domestic_shipping, name='domestic'),
                url(r'^contact-us-volk/$', views.contact_us_volk, name="contact_us_volk"),
                url(r'^contact-us/$', views.contact_us, name="contact_us"),
                url(r'^shopForMe/$', views.vei_shopper, name="vei_shopper"),
                
                url(r'^zeac/contact-us/$', views.zeac_contct_us, name="zeac_contct_us"),

                url(r'^shopping/(?P<action>.+)/(?P<item_id>[-\w]+)/(?P<amount>\d+\.\d{1})/$', views.crud_pay_for_shop, name="crud_pay_for_shop"),
                url(r'^get-dropoff-locations', views.get_dropoff_locations, name="get_dropoff_locations"),
                url(r'^get-location-address', views.get_location_address, name="get_location_address"),
                url(r'^get-country-regions', views.get_country_regions, name="get_country_regions"),
                url(r'^distributor_api_or_rates', views.distributor_api_or_rates, name="distributor_api_or_rates"),
                url(r'^warehouse-address', views.get_warehouse_address, name = "get_warehouse_address"),
                url(r'^my-account/$', views.user_account, name="my_account"),
                url(r'^dst-warehouse-address', views.get_destination_addresses, name = "get_destination_addresses"),
                url(r'^my-shipments/$', views.my_shipments, name="my_shipments"),
                url(r'^volk/shipments/$', views.my_shipments_volk, name="my_shipments_volk"),
                url(r'^my-orders/$', views.my_orders, name="my_orders"),
                url(r'^my-payments/$', views.my_soko_pay_info, name="my_payments"),
                url(r'^volk/payments/$', views.my_soko_pay_info_volk, name="my_payments_volk"),
                url(r'^my-messages/$', views.my_messages, name="my_messages"),
                url(r'^volk/messages/$', views.my_messages_volk, name="my_messages_volk"),
                url(r'^check-avaliable-routes/$', views.check_avaliable_routes, name="check_avaliable_routes"),
                url(r'^my-delivery-addresses/$', views.view_delivery_addresses, name="delivery-addresses"),
                url(r'^volk/delivery-addresses/$', views.view_delivery_addresses_volk, name="delivery_addresses_volk"),
                url(r'^my-mail-bag/$', views.my_mail_bag, name="my_mail_bag"),
                url(r'^volk/mail-bag/$', views.my_mail_bag_volk, name="my_mail_bag_volk"),
                url(r'^paystack/verifyPayment/$',paystack_helpers.verify_payment, name="verifyPayment"),
                url(r'^my-shipment/(\d+)/cancel/$', views.cancel_shipment, name="cancel_shipment"),
                url(r'^FAQ/$', views.marketerFAQ, name = "faq"),
                url(r'^terms-and-conditions/$', views.legal, name = "legal"),
                url(r'^auto-deals/$', views.iaai, name = "iaai"),
                url(r'^waitinglist/$', views.joinwaitinglist, name="joinwaitinglist"),
                url(r'^sendmail/(?P<username>.+)/(?P<subject>.+)/(?P<text>.+)$', views.sendmail, name="sendmail"),
                url(r'^marketer-addon/(?P<action>.+)/$',views.marketer_addons, name="marketer_addons"),
                url(r'^view_edit_shopping_item_order/$',views.view_edit_shopping_item_order, name="view_edit_shopping_item_order"),
                url(r'^edit_shop_request/$',views.edit_shop_request, name="edit_shop_request"),
                
                url(r'^product-view/$', views.product_view, name="product_view"),
                url(r'^detail-view/(?P<item_id>[-\w]+)/$', views.detail_view, name='detail_view'),
                url(r'^cart-view/$', views.cart_view, name="cart_view"),
                url(r'^delete-item/(?P<item_id>[-\w]+)/$', views.delete_item, name='delete_item'),
                url(r'^delete-inv-item/(?P<item_id>[-\w]+)/$', views.del_inv, name='del_inv'),
                url(r'^edit-inv-item/$', views.edit_inv, name='edit_inv'),
                url(r'^inv-edited/$', views.inv_edited, name='inv_edited'),
                url(r'^view-item/$', views.view_item, name='view_item'),
                url(r'^inv-sidebar-category/$', views.inv_sidebar_category, name='inv_sidebar_category'),
                url(r'^checkout/$', views.checkout, name="checkout"),
                url(r'^checking-out-page/$', views.checking_out, name="checking_out"),
                url(r'^order-summary/$', views.order_summary, name="order_summary"),
                url(r'^add-to-cart/$', views.add_to_cart, name="add_to_cart"),
                url(r'^add-inventory/$', views.add_inventory, name="add_inventory"),
                url(r'^inventory/history/(?P<item_id>[0-9]+)$', views.inv_history, name="inventory_history"),
                url(r'^pay-options/$', views.pay_options, name="pay_options"),
                url(r'^order-confirmation/$', views.order_confirmation, name="order_confirmation"),
                url(r'^track_shipments/$', views.track_shipments, name="track_shipments"),
                url(r'^volk/shipment-detail/$', views.shipment_detail_volk, name="shipment_detail_volk"),
                url(r'^volk/detail-shipment/$', views.shipment_detail_number_volk, name="shipment_detail_number_volk"),
                url(r'^volk/shipment-tracker/$', views.my_tracker_volk, name="my_tracker_volk"),
                

                # quick estimate
                url(r'^quick-estimate$', views.quickEstimate, name="quick-estimate"),

                # test label printing
                url(r'^print-label$', views.test_label_printing, name="test_label_printing"),

                # pay-pal
                url(r'^confirm_paypal_payment/$', views.confirm_paypal_payment, name="confirm_paypal_payment"),

                # ebiz
                url(r'^confirm_ebiz_payment/$', views.confirm_ebiz_payment, name="confirm_ebiz_payment"),

                # staff access 
                url(r'^admin-access/(?P<user_obj>.+)/$', group_access.admin_access, name="admin_access"),
                url(r'^zeac/estimate/$', views.get_estimate, name="get_estimate"),
                # url(r'^subscribers-password/$', sokohali_views.change_password, name='change_password'),

]

sokohaliv2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.shortcuts import render, render_to_response

from django.template import RequestContext
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap

from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from general.user_profile import redirect_to_address_activation, redirect_to_address_activation_new
from general.custom_resetpassword import custom_password_reset, custom_password_reset_done
from general.views import homepage

from general.barcode_generator import create_test_barcode


#server error
def server_error(request):
    response = render(request, "500.html")
    response.status_code = 500
    return response

#page not found
def custom_404(request):
    response = render(request, "404.html")
    response.status_code = 404
    return response

#access denied
def access_denied(request):
    return render_to_response("access_denied.html", {},
                              context_instance=RequestContext(request))

handler404 = custom_404

handler500 = server_error


urlpatterns = [

    # url(r'^$', TemplateView.as_view(template_name = 'index.html'), name='homepage'),
    url(r'^$', homepage, name='homepage'),

    #temporary measure
    url(r'^marketer/$', homepage, name='marketer_homepage'),

    url(r'^', include("general.urls", namespace="general")),

    url(r'^adminVolkmann/', include(admin.site.urls)),

    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^payment/', include("payment.urls", namespace="payment")),

    url(r'^', include("veiwallet.urls", namespace="wallet")),

    url(r'^access-denied/$', access_denied, name='access_denied'),

    url(r'session_security/', include('session_security.urls')),

    url(r'^registration/successful/$', TemplateView.as_view(template_name = 'general_client/regsuccessful.html'), name="reg_successful"),

    url(r'^successful/reg/$', TemplateView.as_view(template_name = 'volkmann/registration_successful.html'), name="successful_reg"),

    #Address Activation
    url(r'^redirect_to_address_activation/', redirect_to_address_activation),

    url(r'^redirect_to_address_activation_new/', redirect_to_address_activation_new),

    #import shipping
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),

    #pkg-processor
    url(r'^pkg-processor-api/', include('pkg_processor.urls')),

    url(r'^setup/', include("service_provider.urls", namespace="service_provider")),

    #SokohaliAdmin
    url(r'^backend/', include("sokohaliAdmin.urls", namespace="sokohaliAdmin")),

    url(r'^pay/', include('sokopay.urls', namespace = "soko_pay")),

    url(r'^shopping/', include('shoppingCenter.urls', namespace = "shoppingCenter")),

    url(r'^create-test-barcode/(?P<barcode_id>.+)/', create_test_barcode),

    #change password urls
    url(r'^reset/form/$', TemplateView.as_view(template_name = 'registration/password_reset_email.html')),
    url(r'^resetpassword/passwordsent/$', custom_password_reset_done, name="password_reset_done"),
    #url(r'^resetpassword/$', password_reset, name="password_reset"), custom_password_reset
    url(r'^resetpassword/$', custom_password_reset, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset/done/$', password_reset_complete, name="password_reset_complete"),




]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

general/templates/general_client/login.html
{% extends "base/zaposta_base.html" %}

{% block title %} User Login{% endblock %}
{% block body_head %}
<body>
{% endblock %}


{% block st_content %}
<div class="st-content-inner">
    <!-- extra div for emulating position:fixed of the menu -->
    <!-- Main Section -->
    <section id="main" class="form-outer">
        <div class="hero">
            <div class="container">
                <div class="form show">
                    <div class="inner">

                        <!-- Login Account -->
                        <div class="container" id="login">
                            <div class="col-md-6 promo">
                                <h1>Not a registered customer yet?</h1>
                                <a href="{% url 'general:signup_regular' %}" class="btn full long">Register an Account</a>
                            </div>
                            <form id="login_form" action="" method="POST">
                            {% csrf_token %}
                            <div class="col-md-6 left">
                                <h1>Login</h1>
                                <p style="margin-bottom:0;">Login into your {{ request.storefront_name|title }} account. If you do not have an account please register one.</p>
                                {% if messages %}
                                    <p style="margin-top: 20px;margin-bottom:0;color: red;">
                                    {% for message in messages %} {{message}} <br/>{% endfor %}
                                    </p>
                                {% endif %}
                                <div class="col-md-12 {% if form.username_email.errors %}error{%endif%}">
                                    {{form.username_email}}
                                </div>
                                <div class="col-md-12 {% if form.password.errors %}error{%endif%}">
                                    {{form.password}}
                                </div>
                                <div class="col-md-12 buttons" style="margin-top:9px;">
                                    <button class="btn green" value="Submit" onclick="submitForm('login_form');">Login</button>
                                    <a href="/resetpassword/" class="rst"><span ><i class="fa fa-key" aria-hidden="true"></i></span>Recover Password</a>
                                </div>
                            </div>
                            </form>
                           <!-- <div class="col-md-6 left two">
                                <h1>Reset Password</h1>
                                <p style="margin-bottom:0;">Login into your Sokohali account. If you do not have an account please register one.</p>
                                <div class="col-md-12">
                                    <input type="text" placeholder="Email" />
                                </div>
                                <div class="col-md-12 buttons" style="margin-top:9px;">
                                    <a href="/resetpassword/" class="btn green">Reset Password</a>
                                    <a href="#" class="rst"><span class="glyphicon glyphicon-arrow-left"></span>Back to Login</a>
                                </div>
                            </div>-->
                        </div>
                        <!-- Login Account -->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Main Section -->

    <!-- Other Services -->

    <!-- Other Services -->

    <!-- FOOTER  -->
    {% include "zaposta_snippet/footer_v1.html" %}
    <!-- the content -->
</div>
<!-- /st-content-inner -->
{% endblock %}


{% block script %}


{% endblock %}

general/templates/general_client/quick-estimate.html
{% extends 'base/base_user_account_new.html' %}
{% load humanize %}
{% load staticfiles %}
{% load custom_filters %}
{% load currency %}
{% load account_standing %}

{% block title %}Get a quick estimate{% endblock %}



{% block extra_head %}
    {{ block.super }}
    <style>
        .history.custom{
            background: url("{% static 'sokohali/img/tracking_bus.png' %}") center center no-repeat !important;
        }
        h1{
            font-size: 26px !important;
        }
        h2{
            line-height: 50px !important;
        }
        .in > p{
            color: #fff !important;
        }
        .in .yellow > p{
            color: #453801 !important;
        }

    </style>
{% endblock %}


{% block inner_content %}
        <div class="col-md-8" style="color:#000000;">
          <div class="panel panel-warning" style="background-color:#999999;color: #000000;">
            <div class="panel-heading" style="background-color:#666666; color: #ffffff;"><strong> QUICK ESTIMATE</strong></div>
            <div class="panel-body">
            <!-- <blockquote>Get quick estimate for your packages.</blockquote> -->
          <div class="col-md-3"></div>
          <div class="col-md-9">
          <form  action = "{% url 'general:quick-estimate' %}" method = "POST">
            {% csrf_token %}
              {% if messages  %}
                {% for msg in messages %}
                  <p class="text-danger text-center">{{ msg }}</p>
                {% endfor %}
              {% endif %}
              <div class="row">

              <!-- import countries  -->
              <div class="col-md-12">
                <div class="col-md-6">
                  <strong id="service_from">From:</strong><br/>
                  <select class="form-control" name="country_from" id = "country_from" required>
                    {% for country in countries_origin %}
                      <option value="{{ country }}">{{ country }}</option>
                    {% endfor %}
                  </select>
                  </div>
                 

                <div class="col-md-6">
                  <strong id = "service_to">To:</strong><br/>
                  <select class="form-control" name="country_to" id = "country_to" required>
                    {% for country in countries_destination %}
                      <option value="{{ country }}">{{ country }}</option>
                    {% endfor %}
                  </select>
                  </div>


                <div class="col-md-6">
                  <span id = "select_state_span">
                    <strong id = "state">Destination State</strong><br/>
                    <select class="form-control" name="state" id = "id_slt_state" required>
                      <option value="select state">select state</option>
                    </select>
                  </span>
                  </div>
                  <br/>


                <div class="col-md-6">
                  <span id = "select_state_span">
                    <strong id = "state">Shipping Method</strong><br/>
                    <select class="form-control" name="shipping_method" id = "id_shipping_method" required>
                      <!-- <option value="select state">select state</option> -->
                      <option value="Air">Air Freight</option>
                      <option value="Sea">Sea Freight</option>
                    </select>
                  </span>
                </div>

              </div>
              </div> <!-- main row ends -->

              <br/>
              <div class="col-md-12">
                <strong> Enter Package Dimension</strong>
              </div>
              <div class="col-md-6">
                  <label class="inpl" style="color:#000000;">Length:</label>
                  {{dim_form.box_length}}
              </div>
              <div class="col-md-6">
                  <label class="inpl" style="color:#000000;">Width:</label>
                  {{dim_form.box_width}}
              </div>
              <div class="col-md-6" style="padding-top:30px;">
                  <label class="inpl" style="color:#000000;">Height:</label>
                  {{dim_form.box_height}}
              </div>
              <div class="col-md-6" style="padding-top:30px;">
                  <label class="inpl" style="color:#000000;">Weight:</label>
                  {{dim_form.box_weight_Actual}}
              </div>
              <!-- <div class="col-md-6"> &nbsp; </div> -->
              <div class="col-md-12" style="padding-top:30px;">
                {% for weight_unit in dim_form.weight_unit %}
                <span class="checkb three">
                  {{ weight_unit.tag }}
                  <label>{{ weight_unit.choice_label }} </label>
                </span>
                {% endfor %}
              </div>

        <input type="submit" class="btn btn-dark pull-right" id="btn_get_estimate" value = "Get estimate" />
      </form>
    </div>
  </div>
</div>
</div>
{% endblock inner_content %}





{% block include_acct_standing %}
  <div class="col-md-4">
    {% if packages %}
      <div class="timmer">
          <div class="header" style="padding:10px !important;">
              <strong>PACKAGES CREATED </strong>
          </div>
          <div style="width:100%; padding:0 15px;">
              <table width="100%" border="0" id="pkgs_listing">
                {% for pkg in packages %}
                  <tr>
                      <td>Box {{forloop.counter}}</td>
                      <td>Qty: {{pkg.box_quantity}}</td>
                      <td>{{pkg.box_weight_higher|floatformat:2}}lbs / {{pkg.box_weight_higher_K|floatformat:2}}kg</td>
                      <td>
                        <a href="?delete_pkg={{pkg.pk}}" onclick="return confirm('Are you sure you want to delete this package?');" class="delete" ></a>
                      </td>
                  </tr>
                {% endfor %}
              </table>
          </div>
          <div class="col-md-12">
            <br/><br/>
            <div class="col-md-6">
              <!-- <strong>Shipping Estimate</strong><br/> -->
              <strong>Total Weight: {{total_weight|floatformat:2}}lbs </strong><br/>
              <strong class="text-danger">$ {{ total_estimate_D|floatformat:2|intcomma }} / &#8358; {{ total_estimate_N|floatformat:2|intcomma }} </strong>
            </div>
            <div class="col-md-6">
              <a href="?q=clear_all" onclick="return confirm('Are you sure you want to clear all your packages?');" class="btn yellow two" style="float: left;">Clear All</a>
            </div>

          </div>
      </div>
    {% endif %}
   </div>
{% endblock %}





{% block extra_script %}
    <script>
    function select_estimate(id){
      var service = $("#" + id).val();

      required_fields = ['id_box_length','id_box_height','id_box_box_weight_Actual','id_box_width','id_weight_unit_1']
      import_list = ['country_from','country_to','select_state',]
      export_list = ['deliver_speed','zip_code_to','zip_code_from','value_of_item']

      for (var index = 0; index < required_fields.length; index ++){
          $("#" + required_fields[index]).attr('required', true);
        }

      if (service === "export"){
        for (var index = 0; index < export_list.length; index ++){
          $("#" + export_list[index]).attr('required', true);
        }
        for (var index = 0; index < import_list.length; index ++){
          $("#" + import_list[index]).attr('required', false);
        }
        $("#service_from").html("Country Exporting To:");
        $("#service_to").html("Country Exporting From");
        $("#state").html('Drop-off location');
        $("#export_only").removeClass('hidden');
        }else {
        for (var index = 0; index < export_list.length; index ++){
          $("#" + export_list[index]).attr('required', false);
        }
        for (var index = 0; index < import_list.length; index ++){
          $("#" + import_list[index]).attr('required', true);
        }
        $("#service_from").html('Importing From');
        $("#service_to").html('Importing To');
        $("#state").html('Destination state');
        $("#export_only").addClass('hidden');
      }
  }
</script>

<script>

  $('#country_to').on('change', function(e){
    alert('was changed');
    populateStates('country_to','id_slt_state');
})



</script>

<script>
  $("#id_select_state").on('click', function(){
    var select_content = $("#id_select_state").find(':selected').val();
    var service_type  = $("#estimate_type").find(':selected').val();
    var origin = $("#country_from").find(':selected').val();
    var destination = $("#country_to").find(':selected').val();
    if (select_content === "select state") {
      $("#id_select_state").html('<option style="color:green !important;">fetching states . . .</option>');
      $("#btn_get_estimate").val('fetching states...');
      $("#btn_get_estimate").attr('disabled', true);

      $.ajax({
        type: "GET",
        url:"",
        data:{'service_type':service_type,'origin':origin,'destination':destination, 'action':'fetch_states'},
        success: function(data){
           $("#id_select_state").html(data);
           $("#btn_get_estimate").val('Get Estimate');
           $("#btn_get_estimate").attr('disabled', false);
        },
        error: function(data){

        }
      });
    }
  })
</script>


<script>
  $('body').on('click','#id_slt_state',function(e){
    var from_country = $('#country_from').find(':selected').val();
    var country_to = $('#country_to').find(':selected').val();
    if (from_country == country_to ){
      alert("origin and destination countries cannot be thesame");
    }else{
      alert("origin and destination countries are different carry on")
    }
  })


</script>




<script>
  $("#id_export_state").on('click', function(){
    var select_content = $("#id_select_state").find(':selected').val();
    var service_type  = $("#estimate_type").find(':selected').val();
    var origin = $("#country_from").find(':selected').val();
    var destination = $("#country_to").find(':selected').val();
    if (select_content === "select state") {
      $("#id_select_state").html('<option style="color:green !important;">fetching states . . .</option>');
      $("#btn_get_estimate").val('fetching states...');
      $("#btn_get_estimate").attr('disabled', true);

      $.ajax({
        type: "GET",
        url:"",
        data:{'service_type':service_type,'origin':origin,'destination':destination, 'action':'fetch_states'},
        success: function(data){
           $("#id_select_state").html(data);
           $("#btn_get_estimate").val('Get Estimate');
           $("#btn_get_estimate").attr('disabled', false);
        },
        error: function(data){

        }
      });
    }
  })
</script>
{% endblock %}

general/templates/general_client/signup_regular.html
{% extends "base/zaposta_base.html" %}



{% block title %}User Registration{% endblock %}
{% block body_head %}
<body>
{% endblock %}


{% block st_content %}
<div class="st-content-inner">
	<!-- extra div for emulating position:fixed of the menu -->
	<!-- Main Section -->
	<section id="main" class="form-outer">
		<div class="hero">
			<div class="container">
				<div class="form">
					<div class="inner">
						<!-- Register Account -->
						<div class="container" id="register">
							<div class="col-md-6 promo two" style="min-height: 741px; background-color: #0B71B9;">
								{% if not header_msg %}
								<a href="" class="business_account">
									<div class="inner1">
										<p>Now even for business customers.
											<br/> Register a Business Account for great discount benefits! </p>
										<span></span>
									</div>
									</a>
								{% endif %}
									<h1>Already a registered customer?</h1>
									<a href="{% url 'general:login' %}" class="btn full">Log Into Account</a>
							</div>

							<form id="signup_regular" action="" method="POST">
							{% csrf_token %}

							<!-- Regular Account -->
							<div class="col-md-6 left" style="display: block !important;">
								{% if header_msg %}
									<h1>{{header_msg}}</h1>
								{% else %}
									<h1>Register your Account</h1>
								{% endif %}

								{% if messages %}
									{% for message in messages %}
									<p style="margin-bottom:0; color: green;">{{message}}</p>
									{% endfor %}
								{% else %}
									<p style="margin-bottom:0;">Create your account, it takes less than a minute. If you already have an account, please login.</p>
								{% endif %}

								{% if form.non_field_errors %}

								<span class="error_alert">{{form.non_field_errors}}</span>
								{% endif %}
								{% for field in form %}
									{% if field.errors %}
									<span class="error_alert">{{field.errors}}</span>
									{% endif %}
									<div class="col-md-12 {% if field.errors %}error{% endif %}">
									{{field}}
									</div>
								{% endfor %}

								<div class="col-md-12 buttons" style="margin-top:9px;">
									<!--<a href="#" onclick="submitForm('signup_regular');" class="btn blue">Create Account</a>-->
									<button class="btn blue">Create Account</button>
									<a href="#" onclick="formReset('signup_regular');" class="rst"><span><i class="fa fa-key" aria-hidden="true"></i></span>Reset</a>
								</div>
							</div>

							</form>
							<!-- Regular Account -->

						</div>
						<!-- Register Account -->

					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Main Section -->

	<!-- Other Services -->

	<!-- Other Services -->

	<!-- FOOTER  -->
	{% include "zaposta_snippet/footer_v1.html" %}
	<!-- the content -->
</div>
<!-- /st-content-inner -->
{% endblock %}


{% block script %}
<script src="https://www.google.com/recaptcha/api.js" async="" defer=""></script>

	<script>

		function formReset(form_id){
				$(".input_form").each(function(){
					$(this).css('border-color',  "rgb(161, 161, 161)");
		});
		document.getElementById(form_id).reset();
		return false;
		}

		function changeBorderColor(input_id) {
			document.getElementById(input_id).style.borderColor = "red";
		}
	</script>


{% endblock %}

general/templates/general_client/stripe.html
<html>
	<boby>
		<form action="/your-server-side-code" method="POST">
		  <script
		    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		    data-key="pk_test_m4h3SnA1e9ZTSyBwM3HHqkZ1"
		    data-amount="999"
		    data-name="Demo Site"
		    data-description="Widget"
		    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
		    data-locale="auto">
		  </script>
		</form>
	</body>
</html>