general/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
import bvn_validation
import views, paystack_helpers
import sokohali_views, group_access
import user_profile
from django.views.generic import TemplateView

from general.models import *


user_account = [
                url(r'^user-account/profile/(?P<username>.+)/$', user_profile.profile, name='profile'),
                url(r'^user-account/edit-profile/(?P<username>.+)/$', user_profile.edit_profile, name='edit_profile'),
                url(r'^volk/user-account/profile/(?P<username>.+)/$', user_profile.profile_volk, name='profile_volk'),
                url(r'^volk/user-account/edit-profile/(?P<username>.+)/$', user_profile.edit_profile_volk, name='edit_profile_volk'),
                url(r'^user-account/address-activation/(?P<username>.+)/$', user_profile.address_activation, name='address_activation'),
                url(r'^volk/user-account/address-activation/(?P<username>.+)/$', user_profile.address_activation_new, name='address_activation_new'),
                url(r'^user-account/bvn/verification/$', bvn_validation.verify, name ="verify_bvn"),
                url(r'^user-account/otp/verification/$', bvn_validation.enter_otp, name ="enter_otp"),
                url(r'^user-account/otp/validation/$', bvn_validation.validation_result, name ="validate_otp"),
                url(r'^user-account/resend/otp/$',bvn_validation.resend_otp, name="resend_otp"),
]


sokohali_urls = [
                 url(r'^sokohali/logout/$', sokohali_views.sokohali_logout, name="sokohali-logout"),
                 url(r'^business-settings/$', sokohali_views.business_settings, name="business_settings"),
                 url(r'^about/$', sokohali_views.about, name="about"),
                 url(r'^demo/$', sokohali_views.demopage, name="demopage"),
                 url(r'^contact/$', sokohali_views.contact, name="contact"),
                 url(r'^legal/$', sokohali_views.legal, name="legal"),
                 url(r'^login/$', sokohali_views.LoginSubscriber.as_view(), name="subscriber_login"),
                 url(r'^register/$', sokohali_views.register, name="subscriber_register"),
                 url(r'^sokohali/subscriber-profile/(?P<username>.+)/$', sokohali_views.subscriber_profile, name='subscriber_profile'),
                 url(r'^sokohali/subscriber-edit-profile/(?P<username>.+)/$', sokohali_views.subscriber_edit_profile, name='subscriber_edit_profile'),
                 url(r'^password/$', sokohali_views.change_password, name='change_password'),
                 url(r'^passwordrequest/$', sokohali_views.passwordrequest, name='passwordrequest'),

]

urlpatterns = [

                url(r'^', include(user_account)),
                url(r'^', include(sokohali_urls)),


                url(r'^user/login/$', views.LoginRequest.as_view(), name="login"),
                url(r'^volk/login/$', views.LoginRequestNew.as_view(), name="volkLogin"),
                url(r'^user/logout/$', views.logoutRequest, name="logout"),
                url(r'^user/signup/$', views.userregistration_regular, name="signup_regular"),
                url(r'^user/suspension/$', views.suspension, name="suspension"),
                url(r'^marketer-home/$', views.homepage, name="marketer_home"),
                url(r'^domestic-shipping/$', views.domestic_shipping, name='domestic'),
                url(r'^contact-us-volk/$', views.contact_us_volk, name="contact_us_volk"),
                url(r'^contact-us/$', views.contact_us, name="contact_us"),
                url(r'^shopForMe/$', views.vei_shopper, name="vei_shopper"),
                
                url(r'^zeac/contact-us/$', views.zeac_contct_us, name="zeac_contct_us"),

                url(r'^shopping/(?P<action>.+)/(?P<item_id>[-\w]+)/(?P<amount>\d+\.\d{1})/$', views.crud_pay_for_shop, name="crud_pay_for_shop"),
                url(r'^get-dropoff-locations', views.get_dropoff_locations, name="get_dropoff_locations"),
                url(r'^get-location-address', views.get_location_address, name="get_location_address"),
                url(r'^get-country-regions', views.get_country_regions, name="get_country_regions"),
                url(r'^distributor_api_or_rates', views.distributor_api_or_rates, name="distributor_api_or_rates"),
                url(r'^warehouse-address', views.get_warehouse_address, name = "get_warehouse_address"),
                url(r'^my-account/$', views.user_account, name="my_account"),
                url(r'^dst-warehouse-address', views.get_destination_addresses, name = "get_destination_addresses"),
                url(r'^my-shipments/$', views.my_shipments, name="my_shipments"),
                url(r'^volk/shipments/$', views.my_shipments_volk, name="my_shipments_volk"),
                url(r'^my-orders/$', views.my_orders, name="my_orders"),
                url(r'^my-payments/$', views.my_soko_pay_info, name="my_payments"),
                url(r'^volk/payments/$', views.my_soko_pay_info_volk, name="my_payments_volk"),
                url(r'^my-messages/$', views.my_messages, name="my_messages"),
                url(r'^volk/messages/$', views.my_messages_volk, name="my_messages_volk"),
                url(r'^check-avaliable-routes/$', views.check_avaliable_routes, name="check_avaliable_routes"),
                url(r'^my-delivery-addresses/$', views.view_delivery_addresses, name="delivery-addresses"),
                url(r'^volk/delivery-addresses/$', views.view_delivery_addresses_volk, name="delivery_addresses_volk"),
                url(r'^my-mail-bag/$', views.my_mail_bag, name="my_mail_bag"),
                url(r'^volk/mail-bag/$', views.my_mail_bag_volk, name="my_mail_bag_volk"),
                url(r'^paystack/verifyPayment/$',paystack_helpers.verify_payment, name="verifyPayment"),
                url(r'^my-shipment/(\d+)/cancel/$', views.cancel_shipment, name="cancel_shipment"),
                url(r'^FAQ/$', views.marketerFAQ, name = "faq"),
                url(r'^terms-and-conditions/$', views.legal, name = "legal"),
                url(r'^auto-deals/$', views.iaai, name = "iaai"),
                url(r'^waitinglist/$', views.joinwaitinglist, name="joinwaitinglist"),
                url(r'^sendmail/(?P<username>.+)/(?P<subject>.+)/(?P<text>.+)$', views.sendmail, name="sendmail"),
                url(r'^marketer-addon/(?P<action>.+)/$',views.marketer_addons, name="marketer_addons"),
                url(r'^view_edit_shopping_item_order/$',views.view_edit_shopping_item_order, name="view_edit_shopping_item_order"),
                url(r'^edit_shop_request/$',views.edit_shop_request, name="edit_shop_request"),
                
                url(r'^product-view/$', views.product_view, name="product_view"),
                url(r'^detail-view/(?P<item_id>[-\w]+)/$', views.detail_view, name='detail_view'),
                url(r'^cart-view/$', views.cart_view, name="cart_view"),
                url(r'^delete-item/(?P<item_id>[-\w]+)/$', views.delete_item, name='delete_item'),
                url(r'^delete-inv-item/(?P<item_id>[-\w]+)/$', views.del_inv, name='del_inv'),
                url(r'^edit-inv-item/$', views.edit_inv, name='edit_inv'),
                url(r'^inv-edited/$', views.inv_edited, name='inv_edited'),
                url(r'^view-item/$', views.view_item, name='view_item'),
                url(r'^inv-sidebar-category/$', views.inv_sidebar_category, name='inv_sidebar_category'),
                url(r'^checkout/$', views.checkout, name="checkout"),
                url(r'^checking-out-page/$', views.checking_out, name="checking_out"),
                url(r'^order-summary/$', views.order_summary, name="order_summary"),
                url(r'^add-to-cart/$', views.add_to_cart, name="add_to_cart"),
                url(r'^add-inventory/$', views.add_inventory, name="add_inventory"),
                url(r'^inventory/history/(?P<item_id>[0-9]+)$', views.inv_history, name="inventory_history"),
                url(r'^pay-options/$', views.pay_options, name="pay_options"),
                url(r'^order-confirmation/$', views.order_confirmation, name="order_confirmation"),
                url(r'^track_shipments/$', views.track_shipments, name="track_shipments"),
                url(r'^volk/shipment-detail/$', views.shipment_detail_volk, name="shipment_detail_volk"),
                url(r'^volk/detail-shipment/$', views.shipment_detail_number_volk, name="shipment_detail_number_volk"),
                url(r'^volk/shipment-tracker/$', views.my_tracker_volk, name="my_tracker_volk"),
                

                # quick estimate
                url(r'^quick-estimate$', views.quickEstimate, name="quick-estimate"),

                # test label printing
                url(r'^print-label$', views.test_label_printing, name="test_label_printing"),

                # pay-pal
                url(r'^confirm_paypal_payment/$', views.confirm_paypal_payment, name="confirm_paypal_payment"),

                # ebiz
                url(r'^confirm_ebiz_payment/$', views.confirm_ebiz_payment, name="confirm_ebiz_payment"),

                # staff access 
                url(r'^admin-access/(?P<user_obj>.+)/$', group_access.admin_access, name="admin_access"),
                url(r'^zeac/estimate/$', views.get_estimate, name="get_estimate"),
                # url(r'^subscribers-password/$', sokohali_views.change_password, name='change_password'),

]

shipping/urls.py
from django.conf.urls import patterns, include, url
import views
from sokohaliAdmin.views import *

urlpatterns = [

        #url(r'^$', shipping, name="shipping"),

        #Shippyme Tracking
        #url(r'^tracking/$', fedex_tracking, name="shippyme_tracking"),
        url(r'save-item-data/$', views.save_item_data),
        url(r'del-item-data/$', views.del_item_data),
        url(r'get-user-items/$', views.get_user_items),

        url(r'^retrieve_modal_values', views.retrieve_modal_values, name="retrieve_modal_values"),

        url(r'get-local-freight-price', views.get_local_freight_cost, name='get_local_freight_cost'),

        #Quick Estimate
        #url(r'quick-estimate/$', views.select_package_size, name="quick_estimate"),#select_package)
        #url(r'quick-estimate/clearcart/$', views.quick_estimate_clear_cart, name="quick_estimate_clear_cart"),

        url(r'select-warehouse/$', views.select_warehouse, name="select_warehouse"),

        url(r'select-package-size/$', views.select_package_size, name="select_package"),

        url(r'package-information/$', views.package_information, name="add_item_page"),

        # get item is a package
        # url(r'get-items-in-package/$', views.get_items_in_package, name="get_items_in_package"),

        url(r'^select-shipping-address/$', views.select_shipping_address, name="shipping_address"),
        url(r'^shipping/del-user-item/$', views.user_del_item, name="user_del_item"),

        url(r'payment/$', views.payment_page, name="shipping_payment"),

        url(r'confirmation/$', views.confirmation_page, name="confirmation_page"),

        url(r'invoice/(?P<tracking_id>.+)/$', views.package_invoice_page, name="package_invoice"),

        url(r'courier-label/(?P<tracking_id>.+)/$', views.fetchPackageLabel, name="package_label"),
        # url(r'my-shipment/(?P<pkg_id>[\w+]+)/package-label/$', views.fetchPackageLabel, name="package_label"),

        # #url(r'^shipping-address/send-to/$', add_address, name="select_address"),
        #
        # url(r'^shipping-address/send-to/$', views.shipping_address, name="shipping_address"),
        # url(r'^shipping-address/edit-address/$', views.edit_address),
        #
        url(r'^shipment-manager/dockreceipts/$', views.dockreceipts, name="dockreceipts"),
        url(r'^shipment-manager/dock_form_edit/$', views.dock_form_edit, name="dock_form_edit"),
        url(r'^shipment-manager/dock_edit/$', views.dock_edit, name="dock_edit"),
        url(r'^shipment-manager/dock_template/(?P<tracking_number>.+)/$', views.dock_template, name="dock_template"),
        url(r'^postal-locations/$', views.get_local_distributor_locations, name="local_locations"),
        url(r'^local-pricing/$', views.get_local_distributor_prices, name="local_prices"),
        url(r'^domestic/package/$', views.domestic_package, name="domestic_package"),


]

sokohaliv2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.shortcuts import render, render_to_response

from django.template import RequestContext
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap

from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from general.user_profile import redirect_to_address_activation, redirect_to_address_activation_new
from general.custom_resetpassword import custom_password_reset, custom_password_reset_done
from general.views import homepage

from general.barcode_generator import create_test_barcode


#server error
def server_error(request):
    response = render(request, "500.html")
    response.status_code = 500
    return response

#page not found
def custom_404(request):
    response = render(request, "404.html")
    response.status_code = 404
    return response

#access denied
def access_denied(request):
    return render_to_response("access_denied.html", {},
                              context_instance=RequestContext(request))

handler404 = custom_404

handler500 = server_error


urlpatterns = [

    # url(r'^$', TemplateView.as_view(template_name = 'index.html'), name='homepage'),
    url(r'^$', homepage, name='homepage'),

    #temporary measure
    url(r'^marketer/$', homepage, name='marketer_homepage'),

    url(r'^', include("general.urls", namespace="general")),

    url(r'^adminVolkmann/', include(admin.site.urls)),

    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^payment/', include("payment.urls", namespace="payment")),

    url(r'^', include("veiwallet.urls", namespace="wallet")),

    url(r'^access-denied/$', access_denied, name='access_denied'),

    url(r'session_security/', include('session_security.urls')),

    url(r'^registration/successful/$', TemplateView.as_view(template_name = 'general_client/regsuccessful.html'), name="reg_successful"),

    url(r'^successful/reg/$', TemplateView.as_view(template_name = 'volkmann/registration_successful.html'), name="successful_reg"),

    #Address Activation
    url(r'^redirect_to_address_activation/', redirect_to_address_activation),

    url(r'^redirect_to_address_activation_new/', redirect_to_address_activation_new),

    #import shipping
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),

    #pkg-processor
    url(r'^pkg-processor-api/', include('pkg_processor.urls')),

    url(r'^setup/', include("service_provider.urls", namespace="service_provider")),

    #SokohaliAdmin
    url(r'^backend/', include("sokohaliAdmin.urls", namespace="sokohaliAdmin")),

    url(r'^pay/', include('sokopay.urls', namespace = "soko_pay")),

    url(r'^shopping/', include('shoppingCenter.urls', namespace = "shoppingCenter")),

    url(r'^create-test-barcode/(?P<barcode_id>.+)/', create_test_barcode),

    #change password urls
    url(r'^reset/form/$', TemplateView.as_view(template_name = 'registration/password_reset_email.html')),
    url(r'^resetpassword/passwordsent/$', custom_password_reset_done, name="password_reset_done"),
    #url(r'^resetpassword/$', password_reset, name="password_reset"), custom_password_reset
    url(r'^resetpassword/$', custom_password_reset, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset/done/$', password_reset_complete, name="password_reset_complete"),




]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shipping/templates/shipping/select_shipping_address.html
{% extends "base/zaposta_base.html" %}
{% load humanize %}
{% load activelink %}


{% load account_standing %}
<!-- load operation_countries-->
{% load currency %}

{% block title %}Select Delivery Address{% endblock %}

{% block extra_head %}
  <style>
    .error{
      color: red;
    }
  </style>
{% endblock %}

{% block extra_script %}
    <!-- Special Font for Icons -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<script type="text/javascript" src="{{STATIC_URL}}export/js/jquery.validate.js"></script>
	<script type="text/javascript" src="{{STATIC_URL}}zaposta/js/select_shipping_address.js"></script>

{% endblock %}

{% block extra_head_3 %}
{% endblock %}

{% block body_head %}
<body>
{% endblock %}

{% block st_content %}
<!-- this is the wrapper for the content -->
<div class="st-content-inner">
  <!-- extra div for emulating position:fixed of the menu -->
  <!-- Steps Section -->
  <section id="steps" {% ifstartswith 'shopping:shipping_address' %}class="three tt" {% else %} class="tt" {% endifstartswith %}>
      <div class="white"></div>
      <!-- Page -->
	  <form action="" method="POST">
	  {% csrf_token %}

      <div class="container page">
          {% include 'zaposta_snippet/order_placement_stages.html' with active_page=4 %}

			<div class="col-md-8 content_outer">
				<div class="col-md-12 content" style="padding-bottom:0;">

					<div class="header">Shipping - Shipping Addresses</div>

					<div class="credit two">
						<div class="col-md-12" style="padding-top:30px;">

							<h1>Saved Shipping Addresses</h1>

						</div>
						<div class="col-md-12" style="padding-top:15px;">
							<p>Select a shippping address from your address book or add a new address.</p>
							<!--<p class="alert_green" id="p_select_address"></p>-->
							<p id="p_select_address"></p>
							{% if messages %}
								{% for message in messages%}<p class="error_alert">{{message}}</p>{% endfor %}
							{% endif %}
						</div>


							{% include "shipping_snippet/address_book.html" with addresses=addresses class='two' %}


						<div class="col-md-12" style="padding-top:30px;">
							<h1>New Shipping Addresses</h1>
						</div>
						<div class="col-md-12" style="padding-top:15px;">
							<p>Please click the button below to add a new shipping address to your address book.</p>
						</div>
						<div class="col-md-12" style="text-align:center; padding-top:30px; padding-bottom:30px;">
							<a href="#" id="show_add_address_modal" class="btn yellow" style="float:none; width:50%;">Add New Shipping Address</a>
						</div>
					</div>
				</div>
			</div>

          <!-- Standing -->
          <div class="standing col-md-4">

				<!-- Package List  -->
				 <!--block include_acct_standing
					 ifstartswith 'shopping:shipping_address'
					   zaposta_acct_standing_v1 request 'three'
					 else %}
						{% zaposta_acct_standing_v1 request ''
					 endifstartswith
				 endblock -->
          </div>
          <!-- Standing -->
          <!-- Bottom -->
          <div class="bottom">
			{% ifstartswith 'shopping:shipping_address' %}
				<a href="{% url 'shopping:select_box_and_freight' %}" class="btn prev"><img src="{{STATIC_URL}}zaposta/img/arrow_left.png">Previous Step</a>
				<a href="#" name="proceed" class="btn next blue" onclick='validateAddressSelection("{% url 'shopping:shopping_payment' %}");'>Next Step<img src="{{STATIC_URL}}zaposta/img/arrow_right.png"></a>
			{% else %}
				<a href="{% url 'shipping:select_package' %}" class="btn prev"><img src="{{STATIC_URL}}zaposta/img/arrow_left.png">Previous Step</a>
				<a href="#" class="btn next green" onclick='validateAddressSelection("{% url 'shipping:shipping_payment' %}");'>Next Step<img src="{{STATIC_URL}}zaposta/img/arrow_right.png"></a>
			{% endifstartswith %}
		  </div>
          <!-- Bottom -->
      </div>

	  </form>
      <!-- Page -->
  </section>
  <!-- Steps Section -->

  <!-- FOOTER  -->
   {% include "zaposta_snippet/footer_v2.html" %}
  <!-- FOOTER  -->

  <!-- the content -->
</div>
<!-- /st-content-inner -->
<!--<div class="divLoading" style="display: none;">

</div>-->
{% endblock %}



<!-- block operation_countries
      operatingcountries request.user.is_staff
 endblock -->


{% block edit_shipment_order %}
<!-- Edit Saved Address Modal -->
    <div class="modal clean three" id="eaddr" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                    </button>
                </div>

            </div>
        </div>
    </div>
    <!-- Edit Saved Address Modal -->

    <!-- Add Address Modal -->
    {% include 'shipping_snippet/add_address.html' %}
    <!-- Add Address Modal -->
{% endblock %}

shipping/templates/shipping/select_warehouse_location.html
{% extends "base/zaposta_base.html" %}
{% load humanize %}
{% load activelink %}


{% load account_standing %}
<!--load operation_countries -->
{% load currency %}

{% block title %}Select Warehouse Location{% endblock %}

{% block extra_script %}
    <!-- Special Font for Icons -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	{% if not view_warehouse_location %}
	<script>
		$('.credit.two .panel.addr').click(function () {
			$('.divLoading').addClass('show');
			$(this).parent().parent().find('.panel.addr').removeClass('active');
			$(this).toggleClass('active');
			$('.alert_green').html("Please wait...");

			var warehouse_id = $(this).attr('warehouse_id');

			$.post('', {'warehouse_id': warehouse_id}, function(data){
				$('.alert_green').html(data.result);
				$('.divLoading').removeClass('show');
			});
		});
	</script>
	{% endif %}
{% endblock %}

{% block extra_head_3 %}
{% endblock %}

{% block body_head %}
<body>
{% endblock %}

{% block st_content %}
<!-- this is the wrapper for the content -->
<div class="st-content-inner">
  <!-- extra div for emulating position:fixed of the menu -->
  <!-- Steps Section -->
  <section id="steps" {% ifstartswith 'shopping:shipping_address' %}class="three tt" {% else %} class="tt" {% endifstartswith %}>
      <div class="white"></div>
      <!-- Page -->
	  <form action="" method="POST">
	  {% csrf_token %}

      <div class="container page">
		{% if not view_warehouse_location %}
          {% include 'zaposta_snippet/order_placement_stages.html' with active_page=4 %}
		{% else %}
		<div class="breadcrumbs">
		</div>
        {% endif %}
			<div class="col-md-8 content_outer">
				<div class="col-md-12 content" style="padding-bottom:0;">

					<div class="header">Shipping - Shipping Address</div>

					<div class="credit two">
						<div class="col-md-12" style="padding-top:30px;">
							<h1>Warehouse Location</h1>

						</div>

						<div class="col-md-12" style="padding-top:15px;">
							{% if view_warehouse_location %}
								<p>Please find below a list of your shipping addresses.</p>
							{% else %}
								<p>Please select where your item(s) will be delivered to from our <strong>warehouse locations below</strong>.</p>
							{% endif %}
							<p class="alert_green"></p>
							{% if messages %}
								{% for message in messages%}<p class="error_alert">{{message}}</p>{% endfor %}
							{% endif %}
						</div>


						<div class="addresses_div">
							<div class="col-md-12" style="padding-top:30px;">

							{% for address in warehouses %}
								<div class="panel addr" style="height: 178px;" warehouse_id="{{address.id}}">
									<div style="float: right;">
										{% if address.country == "us" %}
											<img src="{{STATIC_URL}}zaposta/img/usa_flag.png" width="60"/>
										{% elif address.country == "uk" %}
											<img src="{{STATIC_URL}}zaposta/img/uk_flag.png" width="60"/>
										{% endif %}
									</div>
									<!--<a href="#eaddr" id="{{address.pk}}" data-toggle="modal" data-target="#eaddr" class="edit address"></a>
									<a href="#" id="{{address.pk}}" class="delete address"></a>-->
									{% if view_warehouse_location %}
										<h4>{{ address.address|capfirst }}, <br/>{{address.suite_no_prefix}} {{request.user.useraccount.suite_no}}<br />
											{{ address.city|capfirst }}, {{address.state|capfirst}},<br />
										   {{address.country_val|capfirst}}.<br />
										</h4>
									{% else %}
										<h4>{{ address.state|capfirst }},<br />{{ address.country_val|capfirst }}.</h4>
									{% endif %}
								</div>


							{% if forloop.counter|divisibleby:"2" %}

							</div>
							<div class="col-md-12" style="padding-top:15px;">
							{% endif %}
							{% endfor %}

							</div>

						</div>


					</div>
				</div>
			</div>

          <!-- Standing -->
          <div class="standing col-md-4">

				<!-- Package List  -->
				 <!--block include_acct_standing
					 ifstartswith 'shopping:shipping_address'
					   zaposta_acct_standing_v1 request 'three'
					 else
						 zaposta_acct_standing_v1 request ''
					 endifstartswith
				 endblock -->
          </div>
          <!-- Standing -->
          <!-- Bottom -->
          <div class="bottom">
			{% if view_warehouse_location %}
				<a href="{% url 'general:my_account' %}" class="btn prev"><img src="{{STATIC_URL}}zaposta/img/arrow_left.png">Previous Step</a>
			{% else %}
				<a href="{% url 'shipping:add_item_page' %}" class="btn prev"><img src="{{STATIC_URL}}zaposta/img/arrow_left.png">Previous Step</a>
			{% endif %}
				<a href="{% url 'shipping:select_package' %}" class="btn next green" onclick="return validateDeliveryOption();">Next Step<img src="{{STATIC_URL}}zaposta/img/arrow_right.png"></a>

		  </div>

          <!-- Bottom -->
      </div>

	  </form>
      <!-- Page -->
  </section>
  <!-- Steps Section -->

  <!-- FOOTER  -->
   {% include "zaposta_snippet/footer_v2.html" %}
  <!-- FOOTER  -->

  <!-- the content -->
</div>
<!-- /st-content-inner -->

{% endblock %}



{% block operation_countries %}
{% endblock %}


{% block edit_shipment_order %}

{% endblock %}