general/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
import bvn_validation
import views, paystack_helpers
import sokohali_views, group_access
import user_profile
from django.views.generic import TemplateView

from general.models import *


user_account = [
                url(r'^user-account/profile/(?P<username>.+)/$', user_profile.profile, name='profile'),
                url(r'^user-account/edit-profile/(?P<username>.+)/$', user_profile.edit_profile, name='edit_profile'),
                url(r'^volk/user-account/profile/(?P<username>.+)/$', user_profile.profile_volk, name='profile_volk'),
                url(r'^volk/user-account/edit-profile/(?P<username>.+)/$', user_profile.edit_profile_volk, name='edit_profile_volk'),
                url(r'^user-account/address-activation/(?P<username>.+)/$', user_profile.address_activation, name='address_activation'),
                url(r'^volk/user-account/address-activation/(?P<username>.+)/$', user_profile.address_activation_new, name='address_activation_new'),
                url(r'^user-account/bvn/verification/$', bvn_validation.verify, name ="verify_bvn"),
                url(r'^user-account/otp/verification/$', bvn_validation.enter_otp, name ="enter_otp"),
                url(r'^user-account/otp/validation/$', bvn_validation.validation_result, name ="validate_otp"),
                url(r'^user-account/resend/otp/$',bvn_validation.resend_otp, name="resend_otp"),
]


sokohali_urls = [
                 url(r'^sokohali/logout/$', sokohali_views.sokohali_logout, name="sokohali-logout"),
                 url(r'^business-settings/$', sokohali_views.business_settings, name="business_settings"),
                 url(r'^about/$', sokohali_views.about, name="about"),
                 url(r'^demo/$', sokohali_views.demopage, name="demopage"),
                 url(r'^contact/$', sokohali_views.contact, name="contact"),
                 url(r'^legal/$', sokohali_views.legal, name="legal"),
                 url(r'^login/$', sokohali_views.LoginSubscriber.as_view(), name="subscriber_login"),
                 url(r'^register/$', sokohali_views.register, name="subscriber_register"),
                 url(r'^sokohali/subscriber-profile/(?P<username>.+)/$', sokohali_views.subscriber_profile, name='subscriber_profile'),
                 url(r'^sokohali/subscriber-edit-profile/(?P<username>.+)/$', sokohali_views.subscriber_edit_profile, name='subscriber_edit_profile'),
                 url(r'^password/$', sokohali_views.change_password, name='change_password'),
                 url(r'^passwordrequest/$', sokohali_views.passwordrequest, name='passwordrequest'),

]

urlpatterns = [

                url(r'^', include(user_account)),
                url(r'^', include(sokohali_urls)),


                url(r'^user/login/$', views.LoginRequest.as_view(), name="login"),
                url(r'^volk/login/$', views.LoginRequestNew.as_view(), name="volkLogin"),
                url(r'^user/logout/$', views.logoutRequest, name="logout"),
                url(r'^user/signup/$', views.userregistration_regular, name="signup_regular"),
                url(r'^user/suspension/$', views.suspension, name="suspension"),
                url(r'^marketer-home/$', views.homepage, name="marketer_home"),
                url(r'^domestic-shipping/$', views.domestic_shipping, name='domestic'),
                url(r'^contact-us-volk/$', views.contact_us_volk, name="contact_us_volk"),
                url(r'^contact-us/$', views.contact_us, name="contact_us"),
                url(r'^shopForMe/$', views.vei_shopper, name="vei_shopper"),
                
                url(r'^zeac/contact-us/$', views.zeac_contct_us, name="zeac_contct_us"),

                url(r'^shopping/(?P<action>.+)/(?P<item_id>[-\w]+)/(?P<amount>\d+\.\d{1})/$', views.crud_pay_for_shop, name="crud_pay_for_shop"),
                url(r'^get-dropoff-locations', views.get_dropoff_locations, name="get_dropoff_locations"),
                url(r'^get-location-address', views.get_location_address, name="get_location_address"),
                url(r'^get-country-regions', views.get_country_regions, name="get_country_regions"),
                url(r'^distributor_api_or_rates', views.distributor_api_or_rates, name="distributor_api_or_rates"),
                url(r'^warehouse-address', views.get_warehouse_address, name = "get_warehouse_address"),
                url(r'^my-account/$', views.user_account, name="my_account"),
                url(r'^dst-warehouse-address', views.get_destination_addresses, name = "get_destination_addresses"),
                url(r'^my-shipments/$', views.my_shipments, name="my_shipments"),
                url(r'^volk/shipments/$', views.my_shipments_volk, name="my_shipments_volk"),
                url(r'^my-orders/$', views.my_orders, name="my_orders"),
                url(r'^my-payments/$', views.my_soko_pay_info, name="my_payments"),
                url(r'^volk/payments/$', views.my_soko_pay_info_volk, name="my_payments_volk"),
                url(r'^my-messages/$', views.my_messages, name="my_messages"),
                url(r'^volk/messages/$', views.my_messages_volk, name="my_messages_volk"),
                url(r'^check-avaliable-routes/$', views.check_avaliable_routes, name="check_avaliable_routes"),
                url(r'^my-delivery-addresses/$', views.view_delivery_addresses, name="delivery-addresses"),
                url(r'^volk/delivery-addresses/$', views.view_delivery_addresses_volk, name="delivery_addresses_volk"),
                url(r'^my-mail-bag/$', views.my_mail_bag, name="my_mail_bag"),
                url(r'^volk/mail-bag/$', views.my_mail_bag_volk, name="my_mail_bag_volk"),
                url(r'^paystack/verifyPayment/$',paystack_helpers.verify_payment, name="verifyPayment"),
                url(r'^my-shipment/(\d+)/cancel/$', views.cancel_shipment, name="cancel_shipment"),
                url(r'^FAQ/$', views.marketerFAQ, name = "faq"),
                url(r'^terms-and-conditions/$', views.legal, name = "legal"),
                url(r'^auto-deals/$', views.iaai, name = "iaai"),
                url(r'^waitinglist/$', views.joinwaitinglist, name="joinwaitinglist"),
                url(r'^sendmail/(?P<username>.+)/(?P<subject>.+)/(?P<text>.+)$', views.sendmail, name="sendmail"),
                url(r'^marketer-addon/(?P<action>.+)/$',views.marketer_addons, name="marketer_addons"),
                url(r'^view_edit_shopping_item_order/$',views.view_edit_shopping_item_order, name="view_edit_shopping_item_order"),
                url(r'^edit_shop_request/$',views.edit_shop_request, name="edit_shop_request"),
                
                url(r'^product-view/$', views.product_view, name="product_view"),
                url(r'^detail-view/(?P<item_id>[-\w]+)/$', views.detail_view, name='detail_view'),
                url(r'^cart-view/$', views.cart_view, name="cart_view"),
                url(r'^delete-item/(?P<item_id>[-\w]+)/$', views.delete_item, name='delete_item'),
                url(r'^delete-inv-item/(?P<item_id>[-\w]+)/$', views.del_inv, name='del_inv'),
                url(r'^edit-inv-item/$', views.edit_inv, name='edit_inv'),
                url(r'^inv-edited/$', views.inv_edited, name='inv_edited'),
                url(r'^view-item/$', views.view_item, name='view_item'),
                url(r'^inv-sidebar-category/$', views.inv_sidebar_category, name='inv_sidebar_category'),
                url(r'^checkout/$', views.checkout, name="checkout"),
                url(r'^checking-out-page/$', views.checking_out, name="checking_out"),
                url(r'^order-summary/$', views.order_summary, name="order_summary"),
                url(r'^add-to-cart/$', views.add_to_cart, name="add_to_cart"),
                url(r'^add-inventory/$', views.add_inventory, name="add_inventory"),
                url(r'^inventory/history/(?P<item_id>[0-9]+)$', views.inv_history, name="inventory_history"),
                url(r'^pay-options/$', views.pay_options, name="pay_options"),
                url(r'^order-confirmation/$', views.order_confirmation, name="order_confirmation"),
                url(r'^track_shipments/$', views.track_shipments, name="track_shipments"),
                url(r'^volk/shipment-detail/$', views.shipment_detail_volk, name="shipment_detail_volk"),
                url(r'^volk/detail-shipment/$', views.shipment_detail_number_volk, name="shipment_detail_number_volk"),
                url(r'^volk/shipment-tracker/$', views.my_tracker_volk, name="my_tracker_volk"),
                

                # quick estimate
                url(r'^quick-estimate$', views.quickEstimate, name="quick-estimate"),

                # test label printing
                url(r'^print-label$', views.test_label_printing, name="test_label_printing"),

                # pay-pal
                url(r'^confirm_paypal_payment/$', views.confirm_paypal_payment, name="confirm_paypal_payment"),

                # ebiz
                url(r'^confirm_ebiz_payment/$', views.confirm_ebiz_payment, name="confirm_ebiz_payment"),

                # staff access 
                url(r'^admin-access/(?P<user_obj>.+)/$', group_access.admin_access, name="admin_access"),
                url(r'^zeac/estimate/$', views.get_estimate, name="get_estimate"),
                # url(r'^subscribers-password/$', sokohali_views.change_password, name='change_password'),

]

service_provider/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
import views

from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth import views as auth_views


urlpatterns = [

            url(r'^country-settings/$', views.country_settings, name="country_settings"),
            url(r'^customisable-website/activate/$', views.configure_setup, name="configure_setup"),
            url(r'^add-fixed-weight-shipment/$', views.add_fixed_weight_shipment, name="add_fixed_weight_shipment"),
            url(r'^fixed-weight-shipment-items/$', views.fixed_weight_shipment_items, name="fixed_weight_shipment_items"),
            url(r'^view-delivery-routes-rates/$', views.view_delivery_routes_rates, name="view_delivery_routes_rates"),
            url(r'^select-service/$', views.select_service, name="select_service"),
            url(r'^member-info/$', views.get_member_info, name="get_member_info"),
            #url(r'^member-info/(?P<member_type>.+)/(?P<id>\d+)/$', views.get_member_info, name="get_member_info"),
            url(r'^service/shipping/$', views.setup, name="add_service"),
            url(r'^offer/services/$', views.offer_services, name="offer_services"),
            url(r'edit/cost-settings/$', views.edit_cost_settings, name="edit_cost_settings"),
            url(r'^marketing-member/terms-and-cond/$', views.editTermsConditions, name = "editTermsConditions"),
            url(r'^member/Email-template/$', views.emailtemplate, name = "emailtemplate_setup"),
            url(r'^member/Edit/email_template/$', views.edit_emailtemplate, name = "edit_emailform"),
            url(r'^Edit/FAQ/$', views.editFAQ, name = "editFaq"),
            # #change password urls for subscribers
            url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
            url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
            url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                  auth_views.password_reset_confirm, name='password_reset_confirm'),
            url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
            url(r'^service-location/(?P<service_name>\w+?)/(?P<chain_id>\w+?)/$', views.add_warehouse_address, name ="service_location"),
            url(r'cost-settings/$', views.cost_settings, name="cost_settings"),
            url(r'dashboard/details/(?P<chain_id>\w+?)/$', views.dashboard_details, name="dashboard_details"),
            url(r'^loc-distr/$', views.create_local_dist, name='create_local_dist'),
            
]

sokohaliv2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.shortcuts import render, render_to_response

from django.template import RequestContext
from django.views.static import serve
from django.contrib.sitemaps.views import sitemap

from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from general.user_profile import redirect_to_address_activation, redirect_to_address_activation_new
from general.custom_resetpassword import custom_password_reset, custom_password_reset_done
from general.views import homepage

from general.barcode_generator import create_test_barcode


#server error
def server_error(request):
    response = render(request, "500.html")
    response.status_code = 500
    return response

#page not found
def custom_404(request):
    response = render(request, "404.html")
    response.status_code = 404
    return response

#access denied
def access_denied(request):
    return render_to_response("access_denied.html", {},
                              context_instance=RequestContext(request))

handler404 = custom_404

handler500 = server_error


urlpatterns = [

    # url(r'^$', TemplateView.as_view(template_name = 'index.html'), name='homepage'),
    url(r'^$', homepage, name='homepage'),

    #temporary measure
    url(r'^marketer/$', homepage, name='marketer_homepage'),

    url(r'^', include("general.urls", namespace="general")),

    url(r'^adminVolkmann/', include(admin.site.urls)),

    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^payment/', include("payment.urls", namespace="payment")),

    url(r'^', include("veiwallet.urls", namespace="wallet")),

    url(r'^access-denied/$', access_denied, name='access_denied'),

    url(r'session_security/', include('session_security.urls')),

    url(r'^registration/successful/$', TemplateView.as_view(template_name = 'general_client/regsuccessful.html'), name="reg_successful"),

    url(r'^successful/reg/$', TemplateView.as_view(template_name = 'volkmann/registration_successful.html'), name="successful_reg"),

    #Address Activation
    url(r'^redirect_to_address_activation/', redirect_to_address_activation),

    url(r'^redirect_to_address_activation_new/', redirect_to_address_activation_new),

    #import shipping
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),

    #pkg-processor
    url(r'^pkg-processor-api/', include('pkg_processor.urls')),

    url(r'^setup/', include("service_provider.urls", namespace="service_provider")),

    #SokohaliAdmin
    url(r'^backend/', include("sokohaliAdmin.urls", namespace="sokohaliAdmin")),

    url(r'^pay/', include('sokopay.urls', namespace = "soko_pay")),

    url(r'^shopping/', include('shoppingCenter.urls', namespace = "shoppingCenter")),

    url(r'^create-test-barcode/(?P<barcode_id>.+)/', create_test_barcode),

    #change password urls
    url(r'^reset/form/$', TemplateView.as_view(template_name = 'registration/password_reset_email.html')),
    url(r'^resetpassword/passwordsent/$', custom_password_reset_done, name="password_reset_done"),
    #url(r'^resetpassword/$', password_reset, name="password_reset"), custom_password_reset
    url(r'^resetpassword/$', custom_password_reset, name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, name="password_reset_confirm"),
    url(r'^reset/done/$', password_reset_complete, name="password_reset_complete"),




]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

service_provider/templates/setup/add_warehouse_location.html
{% extends 'setup/add-service.html' %}
{% load staticfiles %}


{% block progress_bar_width %}
    style="width: 730px;"
{% endblock %}




{% block back_nxt_div %}
    <div class="right">
        
            <div class="bt prv">
              <a href="{% if origin %}{% url 'service_provider:add_service' %}?page=2&chain={{chain_id}}&origin={{origin}}&destination={{destination}}{% else %}{% url 'service_provider:offer_services' %}{% endif %}"><i class="fa fa-long-arrow-left" aria-hidden="true" style="margin-right:15px;"></i> Back</a>
            </div>

            <!--<div class="bt nxt">-->
            <!--    <a href="?page=2"style="color: #27ae60; text-decoration: none;">Next<i class="fa fa-long-arrow-right" aria-hidden="true" style="margin-left:15px;"></i></a>-->
            <!--</div>-->
    

    
    </div>
    {% endblock %}


{% block inner_page_content %}

<style>
    
    div .pagect{
        overflow:scroll;
    }

</style>

<!-- Page Inner Content/Changes -->
{% if service_name == "warehouse" %}
    <div class="page-content active">
        <!-- Header -->
        <div class="header">
            <div class="left">
                <h1>Warehouse Locations</h1>
                <!--% include 'setup_snippet/route_inner.html' %}-->
                <p> This is where you can view/add all your warehouse locations in the countries configured earlier</p>
            </div>
            <!-- Right Status -->
            <!-- <div class="right">
                <h2 style="float:left;">Issues to fix:</h2>
                <span class="label">4</span>
                <span class="label yellow">1</span>
            </div> -->
            <!-- Right Status -->
        </div>
        <!-- Header -->
        <!-- Page Content -->
        <div class="pagect">
          <div style="float: left;">
            <a href="#" id='add_rate' class="" data-toggle="modal" data-target="#loc" route_id="{{ service_chain.pk }}">
              <i class="fa fa-plus fa-lg" aria-hidden="true">Add Address</i>
            </a>

          </div>
            <div class="steps" style="padding-top: 0px!important; style="overflow-y: scroll;"">
            <table width="100%" border="0" class="" >
                <tr>
                    <th>S/N</th>
                    <th>Address</th>
                    <th>Edit Address</th>
                </tr>
            {% for address in service.get_all_warehouses %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{address.full_address }}</td>
                    <td><a href="#" class='edit_addy' loc_id={{address.pk}}><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></td>
                </tr>
            {% endfor %}
            </table>
              <!-- <p><h3>Setup process completed. Thank you.</h3></p> -->
                  <!-- <div class="row-fluid">
                    <h4>Route: {{ service_chain.origin }} <i class="fa fa-long-arrow-right" aria-hidden="true"></i> {{ route.destination }}</h4>
                  </div> -->

                  <!-- style="position: relative; top: -80px;"  -->

                  <!--% include 'setup_snippet/rates_table.html' with route=service_chain adjust='True' %}-->
                <!-- <div class="progress">
                </div> -->
                <!-- <div class="smcircle">
                    <i class="fa fa-users" aria-hidden="true"></i>
                    <span>Your Customers <br/>(Origin)</span>
                </div> -->

            </div>
            <div class="overlay"></div>

            <!-- Right Side Widget -->
            <div class="widget">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>


            </div>
            <!-- Right Side Widget -->
        </div>
        <!-- Page Content -->

    </div>
    <!-- Page Inner Content/Changes -->


{% elif service_name == "shipper" %}


<!-- Page Inner Content/Changes -->
    <div class="page-content active">
        <!-- Header -->
        <div class="header">
            <div class="left">
                <h1>Shipping Routes</h1>
                
            </div>
            
        </div>
        
        <div class="pagect">
          <div style="float: left;">
            <a href="#" id='add_route' class="" data-toggle="modal" data-target="#route" route_id="{{ service_chain.pk }}">
              <i class="fa fa-plus fa-lg" aria-hidden="true">Add Shipping Route</i>
            </a>

          </div>
            <div class="steps" style="padding-top: 0px!important;">
            <table width="100%" border="0" class="">
                <tr>
                    <th>S/N</th>
                    <th>Shipping Route</th>
                    <th>Edit Route</th>
                </tr>
            {% for route in service.get_all_locations %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ route }}</td>
                    <td><a href="#" class='edit_addy' loc_id={{route.pk}}><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></td>
                </tr>
            {% endfor %}
            </table>
              

            </div>
            <div class="overlay"></div>

            <!-- Right Side Widget -->
            <div class="widget">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>


            </div>
            <!-- Right Side Widget -->
        </div>
        <!-- Page Content -->

    </div>
    <!-- Page Inner Content/Changes -->


{% else %}


<!-- Page Inner Content/Changes -->
    <div class="page-content active">
        <!-- Header -->
        <div class="header">
            <div class="left">
                <h1>Custom Clearing Locations</h1>
                <!--% include 'setup_snippet/route_inner.html' %}-->
            </div>
            
        </div>
        
        <div class="pagect">
          <div style="float: left;">
            <a href="#" id='add_clearing' class="" data-toggle="modal" data-target="#clearing" route_id="{{ service_chain.pk }}">
              <i class="fa fa-plus fa-lg" aria-hidden="true">Add Cost of Clearing</i>
            </a>

          </div>
            <div class="steps" style="padding-top: 0px!important;">
            <table width="100%" border="0" class="">
                <tr>
                    <th>S/N</th>
                    <th>Country & Price</th>
                    <th>Edit</th>
                </tr>
            {% for agent in service.get_all_locations %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ agent }}</td>
                    <td><a href="#" class='edit_addy' loc_id={{agent.pk}}><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></td>
                </tr>
            {% endfor %}
            </table>
               
              </div>
            <div class="overlay"></div>

            <!-- Right Side Widget -->
            <div class="widget">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>


            </div>
            <!-- Right Side Widget -->
        </div>
        <!-- Page Content -->

    </div>
    <!-- Page Inner Content/Changes -->
    {% endif %}
{% endblock %}



{% block modal %}
{% include 'setup_snippet/offer_service_modal.html' %}

{% endblock %}

{% block script %}
 <!--<script src="% static 'soko-admin/js/rates_processing.js' %}"></script>-->
 <script>
    $('body').on('click', '.edit_addy', function(){
       var obj_id = $(this).attr('loc_id');
       var chain_id = $('#chain_id').val();
       var service_name = $('#service_name').val();
       $.ajax({
           url: "{% url 'service_provider:service_location' service_name chain_id %}",
           type: 'GET',
           data: {'obj_id': obj_id},
           success: function(data){
            if (service_name == "shipper"){
               $('#route').replaceWith(data);
               $('#route').modal('show');
            }
            else if(service_name == "clearing_agent"){
               $('#clearing').replaceWith(data);
               $('#clearing').modal('show'); 
            }
            else{
                $('#loc').replaceWith(data);
               $('#loc').modal('show');
           }
          },
          error: function(data){
            console.log('not working');
          }
       });
    });
 </script>
{% endblock %}

service_provider/templates/setup/select_service.html
 {% extends 'setup/add-service.html' %}
{% load staticfiles %}
<!-- progress_bar_width -->
<!--    style="width: 177px;"-->
<!-- endblock -->

{% block progress_bar_width %}
    style="width: 100px;"
{% endblock %}

{% block custom-styles %}
    {{ block.super}}
    <style>
        .row-fluid h4{ font-weight: 600 !important; font-size: 18px !important;}
        .service .col-md-12{padding-top: 60px !important; padding-left: 18px !important; padding-right: 18px !important;}
        .col-md-12.blur h1, p, strong {color: #ebebeb !important;}
        
        .serv_black{
            border-color: black !important;
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

<!--block left_div 
    <div class="left">
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" progress_bar_width style="width: 25%;"  endblock >
               <span></span>
            </div>
        </div>
    </div>
 endblock -->

{% block back_nxt_div %}
    <div class="right">
        <div class="bt prv">
            <!--<a href="#">Back</a>-->
            <a href="{% url 'service_provider:start_setup' %}" style="color: #000; text-decoration: none;"><i class="fa fa-long-arrow-left" aria-hidden="true" style="margin-right:15px;"></i> Back</a>
        </div>
        <div class="bt nxt hidden">
            <a href="{% url 'service_provider:add_service' 'shipping' %}?page=1"style="color: #27ae60; text-decoration: none;">Next <i class="fa fa-long-arrow-right" aria-hidden="true" style="margin-left:15px;"></i></a>
        </div>
    </div>
{% endblock %}

{% block inner_page_content %}
<!-- Page Inner Content/Changes -->
    <div class="page-content active" id="pgfirst">
        <div class="header">
    
            <div class="left">
                <h1 style="line-height: 44px !important;">Select a service</h1>
                
            </div>
            <!-- Right Status -->
            <!--<div class="right">
                <span class="label yellow" style="float:left;">
                    !
                </span>
         url 'service_provider:add_service' 'shipping' page=1
                <h2><a href="{% url 'service_provider:select_service' %}" style="color: #000;">Select Service</a></h2>
            </div>-->
            <!-- Right Status -->
    
        </div>
        <div class="pagect two">
            <!--<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus dapibus, augue non bibendum aliquet, risus ipsum laoreet metus, at pulvinar sem nulla at erat. Aenean ac elit ac felis laoreet malesuada.</p>-->
            
            <!-- Services Row class "hid" when hidden -->
                        <div class="page sv" style="margin-top: 0px !important; width: 130% !important;">
                            <div class="col-md-12">
                                <div class="col-md-4">
                                    <div class="service">
                                        <div class="img">
                                            <!--<img src="{% static 'soko-admin/img/ibk1.png' %}" class="im" />-->
                                            <div class="circle">
                                                <!--<img src="{% static 'soko-admin/img/icon1l.png' %}" />-->
                                            </div>
                                        </div>
                                        <div class="col-md-12 blur">
                                            <h1>Shopping Services</h1>
                                            <p>Shop for your customers. They pay locally, you buy and deliver - <strong>from $50/month</strong></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="service green">
                                        <a href="#">
                                            <div class="img">
                                                <div class="circle">
                                                    <img src="{% static 'soko-admin/img/icon2l.png' %}" />
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <h1>Shipping Services</h1>
                                                <p>Your customers drop off, deliver from shop or location. You ship - <strong>from $50/month</strong></p>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="service">
                                        <div class="img">
                                            <div class="circle"></div>
                                        </div>
                                        <div class="col-md-12 blur">
                                            <h1>Market Place</h1>
                                            <p>Add inventory of popular items. Your customers click to buy. You deliver - <strong>from $25/month</strong>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
            
        </div>
        
    </div>
    <!-- Page Inner Content/Changes -->
{% endblock %}


{% block script %}
    {{ block.super }}
    
    <script>
         $('.service.green').click(function(){
            $('.service.green').removeClass('serv_black')
            //$(this).css('border-color', 'black')
            $(this).toggleClass('serv_black');
            $('.bt.nxt').removeClass('hidden');
            //console.log('here')
         })
    </script>
   
{% endblock %}